# Generated by Django 5.0.3 on 2024-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jenis', models.CharField(choices=[('masuk', 'Uang Masuk'), ('keluar', 'Uang Keluar')], max_length=10)),
                ('deskripsi', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
