# Generated by Django 5.0.3 on 2024-06-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumdes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Laporan',
        ),
    ]
